# Lab 1 – Basic NumPy Operations

This notebook demonstrates basic NumPy operations including array creation, indexing, slicing, reshaping, stacking, broadcasting, matrix multiplication, and solving systems of linear equations.

In [2]:
import numpy as np

### 1. Creating an Array Using `np.arange()`

The `np.arange()` function creates an array of evenly spaced values using a starting value, ending value, and step size.

In [10]:
array1 = np.arange(1, 20, 3)

print(array1)

[ 1  4  7 10 13 16 19]


### 2. Creating a Random Array

The `np.random.rand()` function creates an array containing random numbers between 0 and 1.

In [11]:
random_array = np.random.rand(3)

print(random_array)

[0.88384342 0.48002282 0.28206961]


### 3. Creating and Slicing a 2-D Array

A 2-D NumPy array contains rows and columns. NumPy allows us to select specific rows and columns using slicing.

In [12]:
array2 = np.array([
    [10, 20, 45],
    [30, 12, 16],
    [42, 17, 56]
])

print(array2)

[[10 20 45]
 [30 12 16]
 [42 17 56]]


In [13]:
first_two_rows = array2[:2, :]
print(first_two_rows)

[[10 20 45]
 [30 12 16]]


In [14]:
last_two_rows = array2[-2:, :]

print(last_two_rows)

[[30 12 16]
 [42 17 56]]


### 4. Vertical, Horizontal Stacking and Splitting Arrays

Vertical stacking combines arrays by adding rows, while horizontal stacking combines arrays by adding columns.
NumPy can split a larger array into smaller arrays. Here, the vertically stacked array is divided into two smaller arrays.

In [15]:
array_a = np.array([
    [1, 2],
    [3, 4]
])

array_b = np.array([
    [5, 6],
    [7, 8]
])

print("Array A:")
print(array_a)

print("\nArray B:")
print(array_b)

Array A:
[[1 2]
 [3 4]]

Array B:
[[5 6]
 [7 8]]


In [16]:
vertical_stack = np.vstack((array_a, array_b))

print("Vertical Stack:")
print(vertical_stack)

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
horizontal_stack = np.hstack((array_a, array_b))

print("Horizontal Stack:")
print(horizontal_stack)

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]


In [18]:
split_arrays = np.vsplit(vertical_stack, 2)

print("Split Arrays:")
print(split_arrays)

Split Arrays:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


### 6. Matrix Multiplication

Matrix multiplication is possible when the number of columns in the first matrix matches the number of rows in the second matrix.

In [19]:
X = np.array([
    [5, 7, 2],
    [4, 5, 6],
    [7, 4, 2]
])

Y = np.array([
    [4, 2],
    [6, 2],
    [4, 2]
])

print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)

Shape of X: (3, 3)
Shape of Y: (3, 2)


In [20]:
try:
    result = np.matmul(X, Y)

    print("Matrix multiplication is possible.")
    print("Result:")
    print(result)

except ValueError:
    print("Matrix multiplication is not possible.")

Matrix multiplication is possible.
Result:
[[70 28]
 [70 30]
 [60 26]]


In [21]:
Y_invalid = np.array([
    [4, 2],
    [6, 2]
])

print("Shape of X:", X.shape)
print("Shape of Y_invalid:", Y_invalid.shape)

try:
    result_invalid = np.matmul(X, Y_invalid)

    print("Matrix multiplication is possible.")
    print(result_invalid)

except ValueError:
    print("Matrix multiplication is not possible because the number of columns in X does not match the number of rows in Y_invalid.")

Shape of X: (3, 3)
Shape of Y_invalid: (2, 2)
Matrix multiplication is not possible because the number of columns in X does not match the number of rows in Y_invalid.


### 7. Shape, Dimensions, and Reshaping

The `shape` attribute tells us the size of an array, while `ndim` tells us the number of dimensions. The `reshape()` function changes the shape without changing the data.

In [22]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Shape of x:", x.shape)
print("Number of dimensions of x:", x.ndim)

Shape of x: (3,)
Number of dimensions of x: 1


In [23]:
x_matrix = x.reshape(3, 1)

print("Reshaped x:")
print(x_matrix)

print("Shape of reshaped x:", x_matrix.shape)
print("Number of dimensions of reshaped x:", x_matrix.ndim)

Reshaped x:
[[ 2]
 [-1]
 [-8]]
Shape of reshaped x: (3, 1)
Number of dimensions of reshaped x: 2


In [24]:
y_matrix = y.reshape(3, 1)

print("Reshaped y:")
print(y_matrix)

print("Shape of reshaped y:", y_matrix.shape)
print("Number of dimensions of reshaped y:", y_matrix.ndim)

Reshaped y:
[[ 3]
 [ 1]
 [-2]]
Shape of reshaped y: (3, 1)
Number of dimensions of reshaped y: 2


### 8. Broadcasting

Broadcasting allows NumPy to perform operations between arrays of compatible shapes without explicitly creating additional copies of the data.
Demonstrated the subtraction, multiplication by considering a 3 x 3 matrix

In [20]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

vector = np.array([1, 2, 3])

print("Matrix:")
print(matrix)

print("\nVector:")
print(vector)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector:
[1 2 3]


In [21]:
subtraction_result = matrix - vector

print("Subtraction using broadcasting:")
print(subtraction_result)

Subtraction using broadcasting:
[[0 0 0]
 [3 3 3]
 [6 6 6]]


In [22]:
multiplication_result = matrix * vector

print("Multiplication using broadcasting:")
print(multiplication_result)

Multiplication using broadcasting:
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


## Part B – Systems of Linear Equations

This section uses NumPy linear algebra functions to solve systems of linear equations and determine the number of solutions.

##System 1

In [3]:
A1 = np.array([
    [2, 3, -4],
    [1, -4, 0]
])

b1 = np.array([6, 8])

print("Coefficient matrix:")
print(A1)

print("\nRight-hand side:")
print(b1)

Coefficient matrix:
[[ 2  3 -4]
 [ 1 -4  0]]

Right-hand side:
[6 8]


In [4]:
solution1, residuals1, rank1, singular_values1 = np.linalg.lstsq(
    A1,
    b1,
    rcond=None
)

print("Solution:")
print(solution1)

print("Rank:", rank1)

Solution:
[ 1.6692112 -1.5826972 -1.8524173]
Rank: 2


In [5]:
augmented_A1 = np.column_stack((A1, b1))

rank_A1 = np.linalg.matrix_rank(A1)
rank_augmented_A1 = np.linalg.matrix_rank(augmented_A1)

print("Rank of coefficient matrix:", rank_A1)
print("Rank of augmented matrix:", rank_augmented_A1)

if rank_A1 != rank_augmented_A1:
    print("Number of solutions: No solution")
elif rank_A1 == A1.shape[1]:
    print("Number of solutions: One unique solution")
else:
    print("Number of solutions: Infinitely many solutions")

Rank of coefficient matrix: 2
Rank of augmented matrix: 2
Number of solutions: Infinitely many solutions


##System 2

In [6]:
A2 = np.array([
    [3, -4, 5],
    [-1, 2, -4]
])

b2 = np.array([10, 8])

print("Coefficient matrix:")
print(A2)

print("\nRight-hand side:")
print(b2)

Coefficient matrix:
[[ 3 -4  5]
 [-1  2 -4]]

Right-hand side:
[10  8]


In [7]:
solution2, residuals2, rank2, singular_values2 = np.linalg.lstsq(
    A2,
    b2,
    rcond=None
)

print("Solution:")
print(solution2)

print("Rank:", rank2)

Solution:
[ 7.46067416 -4.62921348 -6.17977528]
Rank: 2


In [8]:
augmented_A2 = np.column_stack((A2, b2))

rank_A2 = np.linalg.matrix_rank(A2)
rank_augmented_A2 = np.linalg.matrix_rank(augmented_A2)

print("Rank of coefficient matrix:", rank_A2)
print("Rank of augmented matrix:", rank_augmented_A2)

if rank_A2 != rank_augmented_A2:
    print("Number of solutions: No solution")
elif rank_A2 == A2.shape[1]:
    print("Number of solutions: One unique solution")
else:
    print("Number of solutions: Infinitely many solutions")

Rank of coefficient matrix: 2
Rank of augmented matrix: 2
Number of solutions: Infinitely many solutions
